[colors]
ansi = [
    '#281f30',
    '#fd57bf',
    '#69bad8',
    '#fa3a6b',
    '#9bc056',
    '#fef359',
    '#9597e2',
    '#d1d1f5',
]
background = '#342840'
brights = [
    '#38343c'
    '#ffaee8',
    '#6bc1e2',
    '#fc8686',
    '#b4d26e',
    '#ffe857',
    '#b99dea',
    '#f3fcff',
]
cursor_bg = '#5957c2'
cursor_border = '#6562b8'
foreground = '#e5cafc'
selection_bg = '#6f93cd'
selection_fg = '#26353a'
scrollbar_thumb = '#2d2753'
split = '#2f2d42'

[meta]
aliases = []
author = 'kdlrose'
name = 'Cosmos'
origin_url = 'https://github.com/kdlrose/moon-queen'
