[colors]
ansi = [
    '#674e78',
    '#d90e7a', 
    '#00a294',
    '#ec8300',
    '#0059dc',
    '#862699',
    '#ff69d3',
    '#c09ebc',
]
background = '#fff1fb'
brights = [
    '#9570b4',
    '#fd30a0', 
    '#30c3b4',
    '#ff9730',
    '#3085ff',
    '#b130cb',
    '#ff6eef',
    '#e7ace3',
]
cursor_bg = '#b43797'
cursor_border = '#b43797'
cursor_fg = '#fdf298'
foreground = '#5a3a57'
selection_bg = '#f2b8da'
selection_fg = '#916ea9'
scrollbar_thumb = '#ffcaf2'
split = '#ffcaf2'

[colors.tab_bar]
background = '#ffe3f8'

[colors.tab_bar.active_tab]
bg_color = '#fff1fb'
fg_color = '#4d3a5a'
italic = true

[colors.tab_bar.inactive_tab]
bg_color = '#ffe3f8'
fg_color = '#4d3a5a'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#edc7ee'
fg_color = '#4d3a5a'
italic = true

[colors.tab_bar.new_tab]
bg_color = '#ffcaf2'
fg_color = '#4d3a5a'

[colors.tab_bar.new_tab_hover]
bg_color = '#edc7ee'
fg_color = '#4d3a5a'
italic = true

[metadata]
aliases = []
author = 'kdlrose'
name = 'Moon Queen Full'
origin_url = 'https://github.com/kdlrose/moon-queen'
